# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
#给邮箱发送信息
GET http://127.0.0.1:8000/mail/test?email=your_email@qq.com

###
#邮箱接收验证码
GET http://127.0.0.1:8000/auth/code?email=your_email@qq.com

###

POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "your_email@qq.com",
  "username": "your_username",
  "password": "your_password",
  "confirm_password": "your_password",
  "code": "your_code"
}


###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "your_email@qq.com",
  "password": "your_password"
}


###

POST http://127.0.0.1:8000/name
Content-Type: application/json

{
  "surname": "张",
  "length": "两字",
  "gender": "男",
  "other": "要尽量大气一点"
}


